layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  popular:
    limit: 3
    exclude:
      forks: false
      projects:
        # - repo-name
  recent:
    limit: 3
    exclude:
      forks: true
      projects:
        # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: spikespaz02
  # keybase: your_username
  linkedin: jacob-birkett-b4882016a
  # medium: your_username
  stackoverflow: 2512078
  telegram: spikespaz
  twitter: spikespaz
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: spikespaz

topics:
  - name: D Language
    web_url: https://github.com/topics/d
    image_url: https://raw.githubusercontent.com/github/explore/7bb9edf7a8b94e13cbe6069a8f2f6a475ea7aaf2/topics/d/d.png
    description: In the last year I have fallen in love with D, a language designed as a successor to C++. While not widely known, this language is powerful and the syntax is beautiful.

  - name: Python 3
    web_url: https://github.com/topics/python3
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
    description: I have about four years of experience with Python. It is my most excersized langauge, being used in the majority of my projects.

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png
    description: JavaScript is my second-best language, being used as long as Python. While not my favorite language (I consider it a necessary evil), it has proven itself useful.
